---
title: "1.0 - Experiment Data Exploration"
author: "Jesús Vélez Santiago"
date: "`r format(Sys.Date(), '%Y-%m')`"
output: 
  html_document:
    theme: readable
    highlight: kate
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  fig.align = "center",
  # dev = "svg",
  fig.retina = 2
)
```

## Libraries

```{r libraries, message=FALSE}
library(tidyverse)
library(ggpubr)
library(ggwaffle)
library(here)
library(glue)
```

## Load Data

### Processed lineages

```{r load_processed_lineages}
processed_lineages_file <- here("data", "processed", "lineages.tsv")
processed_lineages_df <- read_tsv(processed_lineages_file, show_col_types = FALSE) %>% 
  mutate(across(contains("id"), as.character)) %>% 
  glimpse()
```

### Processed tracks

```{r load_processed_track}
tracks_summary_file <- here("data", "processed", "tracks_summary.tsv")
tracks_summary_df <- read_tsv(tracks_summary_file, show_col_types = FALSE) %>% 
  mutate(
    across(contains("id"), as.character),
    across(contains("filamented_"), ~factor(
        .x,
        levels = c(FALSE, TRUE),
        labels = c("Not filamented", "Filamented")
      )
    ),
    across(contains("survived_"), ~factor(
        .x,
        levels = c(FALSE, TRUE),
        labels = c("Not survived", "Survived")
      )
    ),
    cell_status = paste0(filamented_track, " - ", survived_strict) %>% 
      factor()
  ) %>%
  select(experiment_id, id, cell_status, filamented_track, contains("survived")) %>% 
  glimpse()
```

## Minimal preprocessing

```{r minimal_preprocessing}
processed_lineages_df_2 <- processed_lineages_df %>% 
  mutate(
    across(contains("filamented_"), ~factor(
        .x,
        levels = c(FALSE, TRUE),
        labels = c("Not filamented", "Filamented")
      )
    )
  ) %>% 
  inner_join(tracks_summary_df, by = c("experiment_id", "id", "filamented_track")) %>% 
  select(
    experiment_id, id,
    cell_status,
    filamented_track, filamented_at_frame,
    time,
    contains("survived"),
    gfp, ds_red, length
  ) %>%
  relocate(where(is.character), where(is.factor)) %>% 
  glimpse()
```

## Exploratory Data Analysis

### Set default plot style

```{r default_plot_theme}
theme_set(
  theme_bw() +
  theme(legend.position = "top")
)
```

### Samples distribution

```{r}
tracks_summary_df %>% 
  count(experiment_id, cell_status) %>%
  group_by(experiment_id) %>% 
  mutate(
    percentage = n / sum(n) * 100,
    ymax = cumsum(percentage),
    ymin = c(0, head(ymax, -1)),
    labels = paste0(format(percentage, digits = 2), "%"),
    labels_position = (ymax + ymin) / 2,
    total_label = paste0("Total:\n", format(sum(n), big.mark = ","), " cells")
  ) %>% 
  ungroup() %>% 
  glimpse() %>% 
  identity() %>% 
  ggplot(
    aes(
      ymin = ymin,
      ymax = ymax,
      xmin = 3,
      xmax = 4
    )
  ) +
  geom_rect(
    size = 1.5,
    color = "white",
    aes(fill = cell_status)
  ) +
  geom_label(
    x = 2,
    aes(
      y = labels_position,
      label = labels
    ),
    size = 3.5
  ) +
  geom_text(aes(x = -Inf, y = -Inf, label = total_label), hjust = 0.5, vjust = 0.5) +
  facet_grid(. ~ experiment_id) +
  coord_polar(theta = "y") +
  xlim(c(-1, 4)) +
  guides(
    fill = guide_legend(ncol = 2)
  ) +
  theme_void() +
  theme(
    legend.position = "top"
  ) +
  labs(
    fill = "Cell status"
  ) +
  NULL
```
### GFP distribution
```{r gfp_distribution}
processed_lineages_df_2 %>% 
  group_by(experiment_id, id, cell_status) %>% 
  summarize(mean_gfp = mean(gfp), .groups = "drop") %>%
  ggplot(aes(x = mean_gfp, color = cell_status, fill = cell_status)) +
  geom_histogram(alpha = 1 / 3, bins = 30, position = "identity") +
  facet_grid(experiment_id ~ .) +
  guides(
    fill = guide_legend(ncol = 2),
    color = guide_legend(ncol = 2)
  ) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Normalized mean GFP (log10)",
    y = "Number of cells",
    color = "Cell status",
    fill = "Cell status"
  ) +
  NULL
```

### Status by time

```{r,area_chart}
processed_lineages_df %>% 
  count(experiment_id, filamented_at_frame, time) %>% 
  group_by(experiment_id, time) %>% 
  summarize(
    filamented_at_frame = filamented_at_frame,
    percentage = n / sum(n),
    .groups = "drop"
  ) %>% 
  ggplot(aes(x = time, y = percentage, fill = filamented_at_frame)) +
  geom_area(size = 0.5, alpha = 1/1) +
  geom_vline(xintercept = c(60, 140), linetype = "dashed") +
  geom_text(
    data = data.frame(
      x = 73,
      y = 0.8,
      label = "Start",
      experiment_id = "Plasmid"
    ),
    mapping = aes(x = x, y = y, label = label),
    size = 5.64,
    colour = "white",
    fontface = 2,
    inherit.aes = FALSE
  ) +
  geom_text(
    data = data.frame(
      x = 151,
      y = 0.8,
      label = "End",
      experiment_id = "Plasmid"
    ),
    mapping = aes(x = x, y = y, label = label),
    size = 5.64,
    colour = "white",
    fontface = 2,
    inherit.aes = FALSE
  ) +
  facet_grid(experiment_id ~ .) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = scales::percent) +
  theme_bw() +
  theme(
    legend.position = "top",
    panel.spacing.y = unit(1, "lines")
  ) +
  labs(
    x = "Time (minutes)",
    y = "Percentage of cells",
    fill = "Cell status"
  ) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```
### Differences between groups

```{r rain_plot}
library(ggdist)

p_1 <- processed_lineages_df %>% 
  filter(time == 0) %>% 
  ggplot(
    aes(
      x = filamented_track,
      y = length,
      group = filamented_track,
      fill = filamented_track,
      color = filamented_track
    )
  ) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.2,
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .15,
    outlier.shape = NA,
    alpha = 1/3
  ) +
  ggdist::geom_dots(side = "bottom", alpha = 1/10) +
  facet_wrap(experiment_id ~ .) +
  theme_bw() +
  theme(legend.position = "top") +
  labs(
    x = "Cell status",
    y = "Initial length",
    color = "Cell status",
    fill = "Cell status"
  ) +
  scale_y_continuous(limits = c(0, 100)) +
  coord_flip() +
  stat_compare_means(label.y = 60, label.x = 1.5) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)

p_2 <- processed_lineages_df %>% 
  filter(time == 0) %>% 
  ggplot(
    aes(
      x = filamented_track,
      y = gfp,
      group = filamented_track,
      fill = filamented_track,
      color = filamented_track
    ),
    side = "bottom"
  ) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.2,
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .15,
    outlier.shape = NA,
    alpha = 1/3
  ) +
  ggdist::geom_dots(side = "bottom", alpha = 1/10) +
  facet_wrap(experiment_id ~ .) +
  
  theme_bw() +
  theme(legend.position = "top") +
  labs(
    x = "Cell status",
    y = "Initial GFP (log10)",
    color = "Cell status",
    fill = "Cell status"
  ) +
  coord_flip() +
  stat_compare_means(label.y = 2.5, label.x = 1.5) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```

```{r rain_cloud_2}
library(patchwork)
library(ggpubr)

(p_1 / p_2) +
  plot_layout(guides = 'collect')
```

### Metrics distributions

```{r metric_charts}
processed_lineages_df %>% 
  select(experiment_id, filamented_track, time, length, gfp, ds_red) %>% 
  pivot_longer(
    cols = c(length, gfp, ds_red),
    names_to = "metric"
  ) %>%
  mutate(
    metric = case_when(
      metric == "ds_red" ~ "DsRed",
      metric == "gfp" ~ "GFP",
      metric == "length" ~ "Length"
    )
  ) %>% 
  group_by(experiment_id, filamented_track, time, metric) %>%
  summarise(
    ci = list(mean_cl_normal(value)),
    .groups = "drop"
  ) %>% 
  unnest(cols = c(ci)) %>% 
  ggplot(aes(x = time, y = y, ymin= ymin, ymax=ymax, color = filamented_track)) +
  annotate("rect", xmin=60, xmax=140, ymin=-Inf, ymax=Inf, alpha=1/2, color = "transparent", fill = "#FCB565") +
  geom_smooth(method = "loess") +
  facet_grid(metric ~ experiment_id, scales = "free_y") +
  labs(
    x = "Time (minutes)",
    y = "Value",
    color = "Cell status"
  ) +
  theme_bw() +
  theme(legend.position = "top") +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```

### GFP Survival probability

#### Calculation

```{r survival_probability}
gfp_control_hist <- processed_lineages_df %>% 
  ggplot(aes(x = gfp)) +
  geom_histogram(bins = 100)

gfp_hist_data <- gfp_control_hist %>% 
  ggplot_build() %>% 
  pluck("data", 1) %>% 
  select(count, x, xmin, xmax) %>% 
  as_tibble()

gfp_breaks <- gfp_hist_data %>% 
  {c(.$xmin, last(.$xmax))}

survival_probability_df <- processed_lineages_df %>%
  group_by(experiment_id, lineage_id, trap_id, filamented_track) %>% 
  summarise(
    initial_gfp = first(gfp),
    is_long_track = first(centered_frame) < unique(centered_antibiotic_start_frame) &&
      last(centered_frame) > unique(centered_antibiotic_end_frame),
    .groups = "drop"
  ) %>% 
  filter(is_long_track) %>%
  group_by(experiment_id, filamented_track) %>% 
  group_modify(~{
    tibble(
      plot = list(
        ggplot(data = .x, aes(x = initial_gfp)) +
        geom_histogram(breaks = gfp_breaks)
      )
    )
  }) %>% 
  mutate(
    counts = map(plot, ggplot_build),
    counts = map(counts, pluck, "data", 1),
    counts = map(counts, add_column, control_count = gfp_hist_data$count),
    counts = map(counts, select, gfp = x, control_count, count)
  ) %>% 
  unnest(counts) %>% 
  mutate(
    survival_probability = count / control_count,
    #survival_probability = survival_probability / max(survival_probability, na.rm = TRUE)
  ) %>% 
  filter(survival_probability != 0) %>% 
  glimpse()
```

#### Points

```{r survival_probability_plot}
survival_probability_df %>% 
  ggplot(aes(x = gfp, y = survival_probability, color = filamented_track, linetype = experiment_id)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  #facet_grid(. ~ experiment_id) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Initial GFP (log10)",
    y = "Survival probability",
    color = "Cell status",
    linetype = "Experiment"
  ) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```
##### Area


```{r survival_probability_plot_area}
survival_probability_df %>% 
  group_by(filamented_track, gfp) %>% 
  ggplot(aes(x = gfp, y = count, fill = filamented_track, color = filamented_track)) +
  geom_bar(position = "fill", stat="identity") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = scales::percent) +
  #facet_grid(. ~ experiment_id) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Initial GFP (log10)",
    y = "Percentage of cells",
    fill = "Cell status",
    color = "Cell status"
  ) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```

### Length Survival probability

#### Calculation

```{r length_survival_probability}
length_control_hist <- processed_lineages_df %>% 
  ggplot(aes(x = length)) +
  geom_histogram(bins = 100)

length_hist_data <- length_control_hist %>% 
  ggplot_build() %>% 
  pluck("data", 1) %>% 
  select(count, x, xmin, xmax) %>% 
  as_tibble()

length_breaks <- length_hist_data %>% 
  {c(.$xmin, last(.$xmax))}

survival_probability_df <- processed_lineages_df %>%
  group_by(experiment_id, lineage_id, trap_id, filamented_track) %>% 
  summarise(
    initial_length = first(length),
    is_long_track = first(centered_frame) < unique(centered_antibiotic_start_frame) &&
      last(centered_frame) > unique(centered_antibiotic_end_frame),
    .groups = "drop"
  ) %>% 
  filter(is_long_track) %>%
  group_by(experiment_id, filamented_track) %>% 
  group_modify(~{
    tibble(
      plot = list(
        ggplot(data = .x, aes(x = initial_length)) +
        geom_histogram(breaks = length_breaks)
      )
    )
  }) %>% 
  mutate(
    counts = map(plot, ggplot_build),
    counts = map(counts, pluck, "data", 1),
    counts = map(counts, add_column, control_count = length_hist_data$count),
    counts = map(counts, select, length = x, control_count, count)
  ) %>% 
  unnest(counts) %>% 
  mutate(
    survival_probability = count / control_count,
    #survival_probability = survival_probability / max(survival_probability, na.rm = TRUE)
  ) %>% 
  filter(survival_probability != 0) %>% 
  glimpse()
```

#### Points

```{r length_survival_probability_plot}
survival_probability_df %>% 
  filter(survival_probability != 1) %>% 
  ggplot(aes(x = length, y = survival_probability, color = filamented_track, linetype = experiment_id)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  facet_grid(. ~ experiment_id) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Initial length",
    y = "Survival probability",
    color = "Cell status",
    linetype = "Experiment"
  ) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```
##### Area


```{r length_survival_probability_plot_area}
survival_probability_df %>% 
  group_by(filamented_track, length) %>% 
  ggplot(aes(x = length, y = count, fill = filamented_track, color = filamented_track)) +
  geom_bar(position = "fill", stat="identity") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = scales::percent) +
  #facet_grid(. ~ experiment_id) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Initial length",
    y = "Percentage of cells",
    fill = "Cell status",
    color = "Cell status"
  ) +
  scale_color_hue(direction = -1, h.start = 90) +
  scale_fill_hue(direction = -1, h.start = 90)
```